services:
  - type: web
    name: backpack-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
    envVars:
      - key: PORT
        value: 10000

